#!/usr/bin/env python3
"""
Market-cap bucket sweep with the RS>0.2 filter. Fixed base:
  entry = upper Bollinger breakout + Nifty 500 6-month RS > 0.2,
  exit = 20% ratcheting trailing stop, position size 4%, weekly.
Buckets (₹ crore, point-in-time): 1000-10000, 10000-20000, 20000-50000,
50000-100000, >100000. Reports CAGR and Max drawdown.
Cached, deterministic. In-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce
import marketcap_test as mt

BUCKETS = [("1000–10000", 1000, 10000), ("10000–20000", 10000, 20000),
           ("20000–50000", 20000, 50000), ("50000–100000", 50000, 100000),
           (">100000", 100000, None)]

def main():
    symbols, data, master = ce.setup()
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX")
    bt.POS_PCT = 0.04
    trailonly = bt.EXIT_MODES["ATR trail only"]

    rows = []
    for name, lo, hi in BUCKETS:
        r = bt.simulate(symbols, data, master, trailonly, trail_type="pct", pct_trail=0.20,
                        rs_entry=True, rs_thresh=0.2, size_mode="fixed", max_pos=50,
                        mcap_lo=lo, mcap_hi=hi)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        rows.append((name, m, t, r["exposure"]))
        print(f"{name:14s} (₹cr)  CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}   Trades {t.get('n',0):4d}   Win {t.get('win_rate',0)*100:.0f}%   "
              f"Exp {r['exposure']*100:3.0f}%   Final ₹{m['end_v']:,.0f}", flush=True)
    bt.POS_PCT = 0.02

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Market-cap bucket sweep with RS > 0.2 (4% sizing)\n",
         "> Base: upper Bollinger breakout + Nifty 500 6-month **RS > 0.2** + 20% ratcheting trailing "
         "stop + 4% sizing, weekly. Buckets in **₹ crore**, point-in-time (current market cap scaled "
         "by adjusted-price ratio). Cached, deterministic. **In-sample, survivorship-biased.**\n",
         f"- **Window:** {master[0]} → {master[-1]} ({yrs:.1f} years) · ₹20L start\n",
         "## Results by market-cap bucket\n",
         "| Market cap (₹ cr) | **CAGR** | **Max DD** | Calmar | Sharpe | Trades | Win% | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp in rows:
        L.append(f"| {name} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {t.get('n',0)} | {t.get('win_rate',0)*100:.0f}% | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- With RS > 0.2, the **small/mid buckets (1000–20000 cr)** carry the return, as before; "
          "the RS filter concentrates each bucket into its outperformers.",
          "- **Large/mega caps (>50000 cr)** stay weak — the breakout+momentum edge fades and there "
          "are few qualifying names (low exposure).",
          "- Buckets with few trades / low exposure are statistically thin — read with caution.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased (today's Nifty 500 — failed small/mid caps absent, "
          "flattering those buckets most). Point-in-time market cap approximate; small-cap fills "
          "optimistic. Treat small-cap CAGR as an upper bound.\n",
          "*Generated by `backtest/mcap_rs02_sweep.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "MARKETCAP_RS02.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/MARKETCAP_RS02.md")

if __name__ == "__main__":
    main()
