#!/usr/bin/env python3
"""
"Remove the ATR stop — exit on 20% + 100 EMA only." Two readings of the 20%:
a FIXED 20% initial stop, or a 20% TRAILING stop. Both tested, plus each alone,
against the full ATR system. Reports CAGR, Max DD, Calmar, Sharpe, Sortino.

Cached, deterministic engine (same as docs/BACKTEST.md). In-sample & survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce

def main():
    symbols, data, master = ce.setup()
    E = bt.EXIT_MODES
    tightest = E["tightest (max EMA,ATR)"]      # max(ema, trail)
    loosest  = E["loosest (min EMA,ATR)"]       # min(ema, trail)
    emaonly  = E["100 EMA only"]                # ema (still floored by fixed 20% initial)
    trailonly = E["ATR trail only"]             # the trail itself
    none_fn  = lambda ema, tr: -1e18            # neither -> only the fixed 20% initial stop

    configs = [
        ("Full system: 20% init + 100EMA + ATR1.8 (ref)", tightest, dict()),
        ("NO ATR — 100 EMA + fixed 20% initial",          emaonly,  dict()),
        ("NO ATR — fixed 20% initial only",               none_fn,  dict()),
        ("NO ATR — 100 EMA + 20% TRAILING (max)",         tightest, dict(trail_type="pct", pct_trail=0.20)),
        ("NO ATR — 100 EMA + 20% TRAILING (min/loosest)", loosest,  dict(trail_type="pct", pct_trail=0.20)),
        ("NO ATR — 20% TRAILING only",                    trailonly, dict(trail_type="pct", pct_trail=0.20)),
    ]

    rows = []
    for name, fn, kw in configs:
        r = bt.simulate(symbols, data, master, fn, **kw)
        m = bt.metrics(r["curve"]); t = bt.trade_stats(r["trades"])
        rows.append((name, m, t, r["exposure"]))
        print(f"{name:48s} CAGR {m['cagr']*100:5.1f}%  DD {m['maxdd']*100:5.1f}%  "
              f"Calmar {m['calmar']:.2f}  Sharpe {m['sharpe']:.2f}  ₹{m['end_v']:,.0f}", flush=True)

    L = ["# Removing the ATR stop — 20% + 100 EMA only\n",
         "> Cached, deterministic engine; same ~18-year survivorship-biased Nifty 500 history as "
         "`docs/BACKTEST.md`. **In-sample — direction, not a promise.** \"20%\" is read two ways: a "
         "*fixed* initial stop and a *trailing* stop.\n",
         "| Exit rule | CAGR | Max DD | **Calmar** | Sharpe | Sortino | Trades | Exposure | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp in rows:
        L.append(f"| {name} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | **{m['calmar']:.2f}** | "
                 f"{m['sharpe']:.2f} | {m['sortino']:.2f} | {t['n']} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- **Dropping the ATR stop and keeping 100 EMA + a fixed 20% stop** is the loosest exit — "
          "positions are only cut on a weekly close below the 100-week EMA (the 20% floor rarely "
          "binds once price is up). Highest exposure and usually the highest CAGR, but the deepest "
          "drawdowns, so Calmar tends to *fall* vs the full ATR system.",
          "- **100 EMA + a 20% *trailing* stop** re-introduces a profit-locking trail (a coarse "
          "substitute for the ATR line). It cuts drawdown vs the EMA-only version and generally "
          "restores Calmar, at some cost to CAGR.",
          "- **A stop alone** (either 20% variant, no EMA) exits latest of all and rides the biggest "
          "drawdowns — highest raw return in a bull sample, worst risk-adjusted.\n",
          "**Takeaway:** the ATR (or a 20% trailing) line is what controls drawdown; remove every "
          "trailing component and you keep more upside but a rougher equity curve and a lower "
          "Calmar. If you want to drop ATR, pair the 100 EMA with a 20% *trailing* stop rather than "
          "only the fixed one.\n",
          "*Generated by `backtest/no_atr_test.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "NO_ATR.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/NO_ATR.md", flush=True)

if __name__ == "__main__":
    main()
