#!/usr/bin/env python3
"""
Position-size sweep. Fixed rules:
  Entry  : upper Bollinger breakout (weekly close > upper BB 52,2)
  Filter : outperforming Nifty 500 over 6 months (26w relative strength > 0)
  Exit   : 20% ratcheting trailing stop
  Sizing : X% of current equity per position, compounding — X in {2, 4, 5}

Bigger positions = more concentration (2%->~50 names, 4%->~25, 5%->~20) =
higher return potential but deeper drawdown. Reports CAGR and Max drawdown.
Weekly, Nifty 500 universe, ₹20L, 0.25%/side. In-sample & survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce

def main():
    symbols, data, master = ce.setup()
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX")   # Nifty 500, 6-monthly
    trailonly = bt.EXIT_MODES["ATR trail only"]                          # 20% trail only (no EMA)

    rows = []
    for pct in (0.02, 0.04, 0.05):
        bt.POS_PCT = pct
        r = bt.simulate(symbols, data, master, trailonly,
                        trail_type="pct", pct_trail=0.20, rs_entry=True,
                        size_mode="fixed", max_pos=50)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        rows.append((f"{int(pct*100)}% per position (~{int(round(1/pct))} names)", m, t, r["exposure"], r["curve"]))
        print(f"{int(pct*100)}% per position   CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}   Sharpe {m['sharpe']:.2f}   Trades {t['n']}   "
              f"Exp {r['exposure']*100:.0f}%   ₹{m['end_v']:,.0f}", flush=True)
    bt.POS_PCT = 0.02

    benches = {}
    for label, sym in [("Nifty 50", "%5ENSEI"), ("Nifty 500", "%5ECRSLDX")]:
        b = [x for x in bt.fetch_weekly(sym) if x[0] >= master[0]]
        bc = [(x[0], bt.INIT_CAPITAL * x[4] / b[0][4]) for x in b]
        benches[label] = bt.metrics(bc, periods_per_year=52)
        m = benches[label]
        print(f"BENCH {label:14s}  CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}", flush=True)

    n500 = [x for x in bt.fetch_weekly("%5ECRSLDX") if x[0] >= master[0]]
    n500c = [(x[0], bt.INIT_CAPITAL * x[4] / n500[0][4]) for x in n500]
    colors = ["#22a06b", "#2563eb", "#b45309"]
    series = [(f"{r[0].split(' (')[0]} (Calmar {r[1]['calmar']:.2f})", colors[i], r[4])
              for i, r in enumerate(rows)]
    series.append(("Nifty 500 buy&hold", "#9ca3af", n500c))
    bt.make_svg(series, os.path.join(bt.OUTDIR, "results", "possize_equity.svg"),
                "Position size 2%% / 4%% / 5%% — breakout + N500 6M RS + 20% trail (log)")

    L = ["# Position-size sweep — 2% / 4% / 5% per position\n",
         "> **Rules (fixed).** Entry: upper Bollinger breakout (52, 2) **and** outperforming Nifty "
         "500 over 6 months (26-week RS > 0). Exit: 20% ratcheting trailing stop. Sizing: X% of "
         "current equity, compounding. Weekly, Nifty 500 universe, ₹20L, 0.25%/side.\n",
         f"- **Window:** {master[0]} → {master[-1]} ({(master[-1]-master[0]).days/365.25:.1f} years)\n",
         "## Results\n",
         "| Position size | **CAGR** | **Max DD** | Calmar | Sharpe | Trades | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp, _ in rows:
        L.append(f"| {name} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {t['n']} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L.append("")
    L.append("| Benchmark (₹20L buy & hold) | CAGR | Max DD | Calmar |")
    L.append("|---|--:|--:|--:|")
    for label, m in benches.items():
        L.append(f"| {label} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} |")
    L += ["",
          "![position size](../backtest/results/possize_equity.svg)\n",
          "## Read-out\n",
          "- **Bigger positions concentrate the book** (2% ≈ 50 names, 4% ≈ 25, 5% ≈ 20). More "
          "concentration usually **raises both CAGR and Max drawdown** — you ride your best names "
          "harder but feel the corrections more.",
          "- Watch **Calmar**: if it falls as you size up, the extra return isn't paying for the "
          "extra drawdown. The right size is where the drawdown is still one you can actually sit "
          "through.",
          "- 2% is the smoothest ride; 4–5% chase more return at the cost of a rougher curve.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased (today's Nifty 500). Concentrated sizing makes results "
          "lean harder on a few big winners — more fragile out-of-sample.\n",
          "*Generated by `backtest/possize_test.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "POSITION_SIZE.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/POSITION_SIZE.md and backtest/results/possize_equity.svg", flush=True)

if __name__ == "__main__":
    main()
