#!/usr/bin/env python3
"""
Add a market-regime filter: only take entries when NIFTY 50 > its 200-day MA.
Computed on DAILY Nifty 50 (^NSEI), mapped to the weekly decision (as-of Friday).
Your system: breakout (BB 50,2) + RS ratio > 0.2 + market cap 1000-20000 cr + 4%
sizing + 20% ratcheting trailing stop, weekly. With vs without the filter.
Cached, in-sample, survivorship-biased.
"""
import os, sys, datetime as dt, bisect
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
bt.BB_LEN = 50
import calmar_experiments as ce
import marketcap_test as mt

DAY = lambda ts: dt.datetime.utcfromtimestamp(ts).date()

def nifty50_200dma_regime(master, n=200):
    """{weekstart: bool} — Nifty 50 daily close > 200-day SMA, as-of each week's Friday."""
    bars = bt.fetch_weekly("%5ENSEI", "1d", DAY)          # daily Nifty 50
    dts = [b[0] for b in bars]; cl = [b[4] for b in bars]
    flags = []
    run = 0.0
    for i in range(len(bars)):
        run += cl[i]
        if i >= n:
            run -= cl[i - n]
        if i >= n - 1:
            flags.append((dts[i], cl[i] > run / n))
    fd = [f[0] for f in flags]
    reg = {}
    for d in master:
        friday = d + dt.timedelta(days=4)
        j = bisect.bisect_right(fd, friday) - 1
        reg[d] = flags[j][1] if j >= 0 else True
    on = sum(1 for d in master if reg[d]) / len(master)
    print(f"Nifty50 > 200DMA: ON {on*100:.0f}% of weeks", flush=True)
    return reg

def main():
    symbols, data, master = ce.setup()
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX", mode="ratio")
    reg = nifty50_200dma_regime(master)
    bt.POS_PCT = 0.04
    rows = []
    def run(name, **kw):
        r = bt.simulate(symbols, data, master, bt.EXIT_MODES["ATR trail only"],
                        trail_type="pct", pct_trail=kw.pop("trail", 0.20), rs_entry=True, rs_thresh=0.2,
                        size_mode="fixed", max_pos=50, mcap_lo=1000, mcap_hi=20000, **kw)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        rows.append((name, m, t, r["exposure"], r["curve"]))
        print(f"{name:40s} CAGR {m['cagr']*100:5.1f}%  MaxDD {m['maxdd']*100:5.1f}%  Calmar {m['calmar']:.2f}  "
              f"Sharpe {m['sharpe']:.2f}  Trades {t['n']:4d}  Exp {r['exposure']*100:3.0f}%  ₹{m['end_v']:,.0f}", flush=True)

    run("Base (no filter) · 20% trail")
    run("+ Nifty50>200DMA · 20% trail", regime_ok=reg)
    run("Base (no filter) · 10% trail", trail=0.10)
    run("+ Nifty50>200DMA · 10% trail", regime_ok=reg, trail=0.10)
    bt.POS_PCT = 0.02; bt.BB_LEN = 52

    n500 = [x for x in bt.fetch_weekly("%5ECRSLDX") if x[0] >= master[0]]
    n500c = [(x[0], bt.INIT_CAPITAL * x[4] / n500[0][4]) for x in n500]
    bt.make_svg([(f"{rows[0][0]} (Calmar {rows[0][1]['calmar']:.2f})", "#9ca3af", rows[0][4]),
                 (f"{rows[1][0]} (Calmar {rows[1][1]['calmar']:.2f})", "#2563eb", rows[1][4]),
                 ("Nifty 500 buy&hold", "#f59e0b", n500c)],
                os.path.join(bt.OUTDIR, "results", "regime200dma_equity.svg"),
                "Nifty50>200DMA filter vs base (Rs 20L, log scale)")

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Nifty 50 > 200-DMA market filter\n",
         "> Your system: breakout (BB 50,2) + RS ratio > 0.2 + market cap ₹1000–20000 cr + 4% + "
         "ratcheting trailing stop, weekly. Filter: take new entries only when Nifty 50's daily close "
         "is above its 200-day SMA (as-of each week's Friday). Cached, in-sample, survivorship-biased. "
         f"Window {master[0]} → {master[-1]} ({yrs:.1f} yrs).\n",
         "## Results\n",
         "| Setup | CAGR | Max DD | Calmar | Sharpe | Trades | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp, _ in rows:
        L.append(f"| {name} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {t['n']} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- The 200-DMA gate blocks new buys during broad-market downtrends, so it **cuts exposure** "
          "and usually **lowers CAGR**; whether it improves drawdown depends on whether it dodges the "
          "big declines or just misses the sharp recoveries that follow.",
          "- Because your **20% ratcheting trailing stop already exits losers in a downturn**, the "
          "regime gate is largely redundant on the exit side — it mainly throttles re-entry.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased. The 200-DMA is a lagging signal — it flips late at both "
          "tops and bottoms, and can whipsaw in choppy years.\n",
          "*Generated by `backtest/regime200dma.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "REGIME_200DMA.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/REGIME_200DMA.md and backtest/results/regime200dma_equity.svg")

if __name__ == "__main__":
    main()
