#!/usr/bin/env python3
"""
Relative-strength band sweep. Fixed base:
  entry = upper Bollinger breakout, exit = 20% ratcheting trailing stop,
  market cap ₹1000-20000 cr, position size 4%, weekly.
Steps the Nifty-500 6-month outperformance band (rsv in (lo, hi]) and reports
CAGR and Max drawdown for each. Cached, deterministic. In-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce
import marketcap_test as mt

BANDS = [(0.0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5),
         (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0),
         (1.0, None), (0.0, None)]
LABELS = {(1.0, None): ">1.0", (0.0, None): "any >0 (ref)"}
MLO, MHI = 1000, 20000

def main():
    symbols, data, master = ce.setup()
    mc_raw = mt.fetch_marketcaps(sorted(set(symbols)))
    mt.annotate_mcap(data, {s: mc_raw.get(s) for s in symbols})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX")
    bt.POS_PCT = 0.04
    trailonly = bt.EXIT_MODES["ATR trail only"]

    rows = []
    for lo, hi in BANDS:
        r = bt.simulate(symbols, data, master, trailonly, trail_type="pct", pct_trail=0.20,
                        rs_entry=True, rs_thresh=lo, rs_thresh_hi=hi,
                        size_mode="fixed", max_pos=50, mcap_lo=MLO, mcap_hi=MHI)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        label = LABELS.get((lo, hi)) or (f"{lo:g}–{hi:g}" if hi is not None else f">{lo:g}")
        rows.append((label, m, t, r["exposure"]))
        print(f"RS {label:12s}  CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}   Trades {t.get('n',0):4d}   "
              f"Exp {r['exposure']*100:3.0f}%   Final ₹{m['end_v']:,.0f}", flush=True)
    bt.POS_PCT = 0.02

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Outperformance-band sweep (RS vs Nifty 500, 6-month)\n",
         "> Base: upper Bollinger breakout + 20% ratcheting trailing stop + market cap "
         "₹1000–20000 cr + 4% sizing, weekly. Bands are `rsv in (lo, hi]` where rsv = stock's "
         "26-week return minus Nifty 500's 26-week return. Cached, deterministic. **In-sample, "
         "survivorship-biased.**\n",
         f"- **Window:** {master[0]} → {master[-1]} ({yrs:.1f} years) · ₹20L start\n",
         "## Results by outperformance band\n",
         "| RS band | **CAGR** | **Max DD** | Calmar | Sharpe | Trades | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for label, m, t, exp in rows:
        L.append(f"| {label} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {t.get('n',0)} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- **RS measures how far the stock has already outrun the index over 6 months.** Higher "
          "band = stronger momentum at entry.",
          "- Low bands (0–0.1) are barely-outperforming breakouts; very high bands (>0.6) are rare, "
          "so those rows have few trades and low exposure — read them as statistically thin.",
          "- Watch where CAGR peaks vs where drawdown/trade-count stay reasonable: that's the "
          "usable momentum zone. A single narrow band throws away most signals (low exposure), so a "
          "**floor** (e.g. RS > 0.1 or > 0.2, no upper cap) usually beats any tight band.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased; narrow high-RS bands are thin and fragile. Point-in-time "
          "market cap is approximate.\n",
          "*Generated by `backtest/rs_band_sweep.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "RS_BANDS.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/RS_BANDS.md")

if __name__ == "__main__":
    main()
