#!/usr/bin/env python3
"""
Relative-strength FLOOR sweep (cumulative, no upper cap). Fixed base:
  entry = upper Bollinger breakout, exit = 20% ratcheting trailing stop,
  market cap ₹1000-20000 cr, position size 4%, weekly.
Steps the Nifty-500 6-month outperformance floor: enter only if rsv > floor.
Reports CAGR and Max drawdown. Cached, deterministic. In-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce
import marketcap_test as mt

FLOORS = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
MLO, MHI = 1000, 20000

def main():
    symbols, data, master = ce.setup()
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX")
    bt.POS_PCT = 0.04
    trailonly = bt.EXIT_MODES["ATR trail only"]

    rows = []
    for f in FLOORS:
        r = bt.simulate(symbols, data, master, trailonly, trail_type="pct", pct_trail=0.20,
                        rs_entry=True, rs_thresh=f, rs_thresh_hi=None,
                        size_mode="fixed", max_pos=50, mcap_lo=MLO, mcap_hi=MHI)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        rows.append((f, m, t, r["exposure"]))
        print(f"RS > {f:.1f}   CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}   Sharpe {m['sharpe']:.2f}   Trades {t.get('n',0):4d}   "
              f"Exp {r['exposure']*100:3.0f}%   Final ₹{m['end_v']:,.0f}", flush=True)
    bt.POS_PCT = 0.02

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Outperformance FLOOR sweep (RS > threshold, cumulative)\n",
         "> Base: upper Bollinger breakout + 20% ratcheting trailing stop + market cap "
         "₹1000–20000 cr + 4% sizing, weekly. Enter only if `rsv > floor`, where rsv = stock's "
         "26-week return minus Nifty 500's 26-week return (no upper cap). Cached, deterministic. "
         "**In-sample, survivorship-biased.**\n",
         f"- **Window:** {master[0]} → {master[-1]} ({yrs:.1f} years) · ₹20L start\n",
         "## Results by RS floor\n",
         "| RS floor | **CAGR** | **Max DD** | Calmar | Sharpe | Trades | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    best = max(rows, key=lambda x: x[1]["calmar"])
    for f, m, t, exp in rows:
        star = " ⭐" if (f, m, t, exp) == best else ""
        L.append(f"| RS > {f:.1f}{star} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | "
                 f"**{m['calmar']:.2f}** | {m['sharpe']:.2f} | {t.get('n',0)} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- A **floor** keeps every stock above the threshold (unlike a narrow band), so it stays "
          "well invested and captures the strongest leaders.",
          "- Raising the floor trades some CAGR/exposure for lower drawdown; find where Calmar peaks.",
          "- Compare to the earlier narrow-band sweep (`docs/RS_BANDS.md`): floors dominate bands "
          "because they don't discard the strong movers above the band.\n",
          "*Generated by `backtest/rs_floor_sweep.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "RS_FLOORS.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/RS_FLOORS.md")

if __name__ == "__main__":
    main()
