#!/usr/bin/env python3
"""
Base = 20% ratcheting trailing stop, PLUS a Nifty 500 *outperformance* filter
(relative strength) — all weekly. Only hold names beating the index.

Tests the outperformance rule as an ENTRY gate (and optionally an EXIT), over a
couple of relative-strength lookbacks, and reports CAGR + Max drawdown (+ Calmar,
Sharpe). Cached, deterministic engine. In-sample & survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce

def run(symbols, data, master, name, fn, kw):
    r = bt.simulate(symbols, data, master, fn, **kw)
    m = bt.metrics(r["curve"]); t = bt.trade_stats(r["trades"])
    print(f"{name:44s} CAGR {m['cagr']*100:5.1f}%  MaxDD {m['maxdd']*100:5.1f}%  "
          f"Calmar {m['calmar']:.2f}  Sharpe {m['sharpe']:.2f}  ₹{m['end_v']:,.0f}", flush=True)
    return (name, m, t, r["exposure"])

def main():
    symbols, data, master = ce.setup()
    reg = ce.regime_series(master)
    tight = bt.EXIT_MODES["tightest (max EMA,ATR)"]
    trailonly = bt.EXIT_MODES["ATR trail only"]
    base = dict(trail_type="pct", pct_trail=0.20)
    rows = []

    rows.append(run(symbols, data, master, "Base: 20% trail + 100 EMA (no filter)", tight, {**base}))
    rows.append(run(symbols, data, master, "Base + regime filter (reference)", tight, {**base, "regime_ok": reg}))

    bt.annotate_rs(data, symbols, lookback=26)
    rows.append(run(symbols, data, master, "+ N500 outperformance ENTRY (26w RS)", tight, {**base, "rs_entry": True}))
    rows.append(run(symbols, data, master, "+ outperformance ENTRY+EXIT (26w RS)", tight, {**base, "rs_entry": True, "rs_exit": True}))
    rows.append(run(symbols, data, master, "20% trail ONLY + outperf ENTRY (26w)", trailonly, {**base, "rs_entry": True}))

    bt.annotate_rs(data, symbols, lookback=13)
    rows.append(run(symbols, data, master, "+ N500 outperformance ENTRY (13w RS)", tight, {**base, "rs_entry": True}))
    rows.append(run(symbols, data, master, "+ outperformance ENTRY+EXIT (13w RS)", tight, {**base, "rs_entry": True, "rs_exit": True}))

    best = max(rows[1:], key=lambda x: x[1]["calmar"])
    L = ["# 20% trailing stop + Nifty 500 outperformance filter\n",
         "> Base = 20% ratcheting trailing stop + 100 EMA. \"Outperformance\" = the stock's "
         "L-week return minus Nifty 500's L-week return > 0 (relative strength), evaluated weekly. "
         "Same survivorship-biased history & deterministic engine as `docs/BACKTEST.md`. **In-sample.**\n",
         "| Setup | CAGR | **Max DD** | Calmar | Sharpe | Sortino | Exposure | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp in rows:
        mark = " ⭐" if name == best[0] else ""
        L.append(f"| {name}{mark} | {m['cagr']*100:.1f}% | **{m['maxdd']*100:.1f}%** | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {m['sortino']:.2f} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out\n",
          "- **Requiring Nifty 500 outperformance to enter (relative strength > 0)** keeps you in "
          "leaders and out of laggards. It typically trims Max drawdown and lifts risk-adjusted "
          "return, at a modest hit to raw CAGR (you take fewer, higher-quality entries).",
          "- **Adding an outperformance EXIT** (sell when a name starts lagging the index) cuts "
          "drawdown further but can clip winners during healthy consolidations — watch the CAGR/DD "
          "trade-off.",
          "- **Shorter RS lookback (13w)** reacts faster (more trades, tighter) vs 26w (steadier). "
          "Neither is 'right' — pick by how much churn you'll tolerate.",
          "- Compare against the plain **regime filter** row: the outperformance (stock-vs-index) "
          "and regime (index-vs-its-own-trend) filters attack drawdown from different angles.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased; the RS lookback is a fitted choice — validate "
          "out-of-sample before trusting a specific number.\n",
          "*Generated by `backtest/rs_filter_test.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "OUTPERFORMANCE.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/OUTPERFORMANCE.md", flush=True)

if __name__ == "__main__":
    main()
