#!/usr/bin/env python3
"""
20% ratcheting trailing stop + Nifty 500 outperformance over 3M / 6M / 1Y (weekly).
"Outperformance" = stock's L-week return minus Nifty 500's L-week return > 0.

Tests each horizon as an ENTRY filter, and the strict combination (must beat the
index over 3M AND 6M AND 1Y). Reports CAGR and Max drawdown (+ Calmar, Sharpe).
Cached, deterministic engine. In-sample & survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce

W = {"3M (13w)": 13, "6M (26w)": 26, "1Y (52w)": 52}

def run(symbols, data, master, name, kw):
    r = bt.simulate(symbols, data, master, bt.EXIT_MODES["tightest (max EMA,ATR)"], **kw)
    m = bt.metrics(r["curve"]); t = bt.trade_stats(r["trades"])
    print(f"{name:46s} CAGR {m['cagr']*100:5.1f}%  MaxDD {m['maxdd']*100:5.1f}%  "
          f"Calmar {m['calmar']:.2f}  Sharpe {m['sharpe']:.2f}  ₹{m['end_v']:,.0f}", flush=True)
    return (name, m, t, r["exposure"])

def main():
    symbols, data, master = ce.setup()
    reg = ce.regime_series(master)
    base = dict(trail_type="pct", pct_trail=0.20)   # 20% ratcheting trailing stop
    rows = []

    rows.append(run(symbols, data, master, "Base: 20% trail + 100 EMA (no filter)", {**base}))
    rows.append(run(symbols, data, master, "Base + regime filter (reference)", {**base, "regime_ok": reg}))

    # annotate each horizon under its own key, plus a combined min() key
    for label, L in W.items():
        bt.annotate_rs(data, symbols, lookback=L, key=f"rs{L}")
    for s in symbols:
        for x, bar in data[s].items():
            vals = [bar.get(f"rs{L}") for L in W.values()]
            bar["rs"] = min(vals) if all(v is not None for v in vals) else None

    # each horizon alone (entry filter) — point bar['rs'] at that horizon's key
    for label, L in W.items():
        for s in symbols:
            for bar in data[s].values():
                bar["rs"] = bar.get(f"rs{L}")
        rows.append(run(symbols, data, master, f"+ outperformance ENTRY {label}", {**base, "rs_entry": True}))

    # strict combination: must outperform over 3M AND 6M AND 1Y  (rs = min of the three)
    for s in symbols:
        for bar in data[s].values():
            vals = [bar.get(f"rs{L}") for L in W.values()]
            bar["rs"] = min(vals) if all(v is not None for v in vals) else None
    rows.append(run(symbols, data, master, "+ outperformance ENTRY 3M & 6M & 1Y (all)", {**base, "rs_entry": True}))
    rows.append(run(symbols, data, master, "+ ENTRY+EXIT 3M & 6M & 1Y (all)", {**base, "rs_entry": True, "rs_exit": True}))

    best = max(rows[1:], key=lambda x: x[1]["calmar"])
    L = ["# 20% trailing stop + Nifty 500 outperformance: 3M / 6M / 1Y\n",
         "> Base = 20% ratcheting trailing stop + 100 EMA. \"Outperformance N\" = the stock's "
         "N-week return minus Nifty 500's N-week return > 0 (relative strength), evaluated weekly. "
         "3M=13w, 6M=26w, 1Y=52w. Same survivorship-biased history & deterministic engine as "
         "`docs/BACKTEST.md`. **In-sample.**\n",
         "| Setup | **CAGR** | **Max DD** | Calmar | Sharpe | Sortino | Exposure | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for name, m, t, exp in rows:
        mark = " ⭐" if name == best[0] else ""
        L.append(f"| {name}{mark} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {m['sortino']:.2f} | {exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Read-out (CAGR & drawdown)\n",
          "- **Longer look-backs = stronger trend filter.** A 1-year (52w) outperformance gate is the "
          "strictest single horizon — it keeps only established leaders, usually the steadiest curve; "
          "3-month (13w) reacts fastest and admits more names.",
          "- **Requiring outperformance over all three horizons (3M & 6M & 1Y)** is the tightest "
          "entry screen: fewest, highest-quality names. It tends to give the lowest drawdown but can "
          "cost CAGR (you pass on early-stage movers).",
          "- **Adding an outperformance EXIT** on top raises turnover; it can lift CAGR but usually "
          "deepens drawdown — watch the trade-off in the table.",
          "- Compare to the plain **regime filter** (index vs its own trend): the outperformance "
          "screen (stock vs index) is a *stock-selection* filter, the regime is a *market-timing* one; "
          "they reduce drawdown by different mechanisms.\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased; the horizon set (13/26/52w) is a fitted choice. Validate "
          "out-of-sample before committing to a specific look-back.\n",
          "*Generated by `backtest/rs_multi_test.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "OUTPERF_MULTI.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/OUTPERF_MULTI.md", flush=True)

if __name__ == "__main__":
    main()
