#!/usr/bin/env python3
"""
Exact screener definition (as supplied):
  1. (Close / Close_26w) / (NIFTY500 / NIFTY500_26w) - 1  >  0.2   (RS RATIO)
  2. Weekly close crossed above the Upper Bollinger Band (50, 2)
  3. Market cap > 1000 and < 20000 (₹ crore)
Position size 4%, weekly. Exit tested at 20% (stated) and 10% ratcheting trailing.
Also compares RS-ratio vs the earlier RS-difference. Cached, in-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
bt.BB_LEN = 50                      # screener uses Bollinger (50, 2)
import calmar_experiments as ce
import marketcap_test as mt

def run(symbols, data, master, pct, label):
    r = bt.simulate(symbols, data, master, bt.EXIT_MODES["ATR trail only"],
                    trail_type="pct", pct_trail=pct, rs_entry=True, rs_thresh=0.2,
                    size_mode="fixed", max_pos=50, mcap_lo=1000, mcap_hi=20000)
    m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
    print(f"{label:38s} CAGR {m['cagr']*100:5.1f}%  MaxDD {m['maxdd']*100:5.1f}%  Calmar {m['calmar']:.2f}  "
          f"Sharpe {m['sharpe']:.2f}  Trades {t['n']:4d}  Win {t['win_rate']*100:.0f}%  ₹{m['end_v']:,.0f}", flush=True)
    return label, m, t, r["curve"]

def main():
    symbols, data, master = ce.setup()          # indicators built with BB(50,2)
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.POS_PCT = 0.04
    rows = []

    print("--- EXACT screener: RS RATIO > 0.2, BB(50,2), mcap 1000-20000, 4% ---")
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX", mode="ratio")
    rows.append(run(symbols, data, master, 0.20, "RS ratio · 20% trail (as stated)"))
    rows.append(run(symbols, data, master, 0.10, "RS ratio · 10% trail (better exit)"))

    print("\n--- for reference: RS DIFFERENCE > 0.2 (what I used before) ---")
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX", mode="diff")
    rows.append(run(symbols, data, master, 0.20, "RS diff · 20% trail"))
    rows.append(run(symbols, data, master, 0.10, "RS diff · 10% trail"))
    bt.POS_PCT = 0.02; bt.BB_LEN = 52

    n500 = [x for x in bt.fetch_weekly("%5ECRSLDX") if x[0] >= master[0]]
    n500c = [(x[0], bt.INIT_CAPITAL * x[4] / n500[0][4]) for x in n500]
    bt.make_svg([(f"{rows[0][0]} (Calmar {rows[0][1]['calmar']:.2f})", "#2563eb", rows[0][3]),
                 (f"{rows[1][0]} (Calmar {rows[1][1]['calmar']:.2f})", "#22a06b", rows[1][3]),
                 ("Nifty 500 buy&hold", "#f59e0b", n500c)],
                os.path.join(bt.OUTDIR, "results", "screener_exact_equity.svg"),
                "Exact screener: RS ratio>0.2, BB(50,2), 1000-20000cr, 4% (log)")

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Exact screener backtest (RS ratio, BB 50,2, ₹1000–20000 cr)\n",
         "> Entry (all must pass, cash segment, weekly):\n",
         "> 1. `(Close / Close₂₆w) / (NIFTY500 / NIFTY500₂₆w) − 1 > 0.2` (RS **ratio**)",
         "> 2. Weekly close crossed **above the Upper Bollinger Band (50, 2)**",
         "> 3. Market cap **> 1000** and **< 20000** (₹ crore)\n",
         "> Sizing 4%, weekly. Exit = ratcheting trailing stop. Cached, deterministic. "
         f"Window {master[0]} → {master[-1]} ({yrs:.1f} yrs). **In-sample, survivorship-biased.**\n",
         "## Results\n",
         "| Setup | CAGR | Max DD | Calmar | Sharpe | Trades | Win% | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for label, m, t, _ in rows:
        L.append(f"| {label} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | {m['calmar']:.2f} | "
                 f"{m['sharpe']:.2f} | {t['n']} | {t['win_rate']*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "## Notes\n",
          "- **RS ratio vs difference:** your screener divides the stock's 26-week growth ratio by "
          "the index's (multiplicative); I had used the return *difference*. Both are ~equivalent when "
          "the index is roughly flat, and diverge when the index moved a lot; the table shows the "
          "small effect on results.",
          "- **Bollinger (50, 2)** is used here as the screener specifies (vs 52 in the official "
          "indicator legend) — negligible difference.",
          "- Exit is not part of your screen; the 10% trailing stop remains the better exit vs 20%.\n",
          "*Generated by `backtest/screener_exact.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "SCREENER_EXACT.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/SCREENER_EXACT.md and backtest/results/screener_exact_equity.svg")

if __name__ == "__main__":
    main()
