#!/usr/bin/env python3
"""
Highest winners and their holding (retention) period.
Config = the exact screen: RS ratio > 0.2, Bollinger (50,2), market cap
1000-20000 cr, 4% sizing, weekly, 20% ratcheting trailing stop (lets winners run).
Ranks trades by return and reports each winner's holding period.
Cached, in-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
bt.BB_LEN = 50
import calmar_experiments as ce
import marketcap_test as mt

def clean(s):
    return s.replace(".NS", "").replace("%26", "&")

def main():
    symbols, data, master = ce.setup()
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX", mode="ratio")
    bt.POS_PCT = 0.04
    r = bt.simulate(symbols, data, master, bt.EXIT_MODES["ATR trail only"],
                    trail_type="pct", pct_trail=0.20, rs_entry=True, rs_thresh=0.2,
                    size_mode="fixed", max_pos=50, mcap_lo=1000, mcap_hi=20000)
    trades = r["trades"]
    wins = [t for t in trades if t["ret"] > 0]
    losses = [t for t in trades if t["ret"] <= 0]
    top = sorted(trades, key=lambda t: -t["ret"])[:25]

    def yrs(w): return w / 52.0
    print(f"Total trades {len(trades)} · winners {len(wins)} ({len(wins)/len(trades)*100:.0f}%) · losers {len(losses)}")
    print(f"Avg hold — winners {sum(t['weeks'] for t in wins)/len(wins):.0f}w ({yrs(sum(t['weeks'] for t in wins)/len(wins)):.1f}y) · "
          f"losers {sum(t['weeks'] for t in losses)/len(losses):.0f}w ({yrs(sum(t['weeks'] for t in losses)/len(losses)):.1f}y)")
    top10 = sorted(trades, key=lambda t: -t["ret"])[:10]
    print(f"Avg hold — top 10 winners {sum(t['weeks'] for t in top10)/10:.0f}w ({yrs(sum(t['weeks'] for t in top10)/10):.1f}y)")
    print("\nTop 25 winners:")
    print(f"{'#':>2} {'Symbol':<12} {'Entry':<11} {'Exit':<11} {'Return%':>8} {'Held(w)':>7} {'Held(y)':>7} {'P&L ₹':>12}")
    for i, t in enumerate(top, 1):
        print(f"{i:>2} {clean(t['sym']):<12} {str(t['entry_date']):<11} {str(t['exit_date']):<11} "
              f"{t['ret']*100:>7.0f}% {t['weeks']:>7} {yrs(t['weeks']):>7.1f} {t['pnl']:>12,.0f}")

    # holding-period buckets for winners
    buckets = [(0,26,"<6m"),(26,52,"6-12m"),(52,104,"1-2y"),(104,156,"2-3y"),(156,260,"3-5y"),(260,9999,">5y")]
    dist = {lab: sum(1 for t in wins if lo <= t["weeks"] < hi) for lo,hi,lab in buckets}

    L = ["# Highest winners & their holding (retention) period\n",
         "> Config: RS ratio > 0.2 + Bollinger (50,2) breakout + market cap ₹1000–20000 cr + 4% "
         "sizing + 20% ratcheting trailing stop, weekly. Cached, in-sample, survivorship-biased.\n",
         f"- Trades: {len(trades)} · winners {len(wins)} ({len(wins)/len(trades)*100:.0f}%) · losers {len(losses)}",
         f"- **Avg holding — winners: {sum(t['weeks'] for t in wins)/len(wins):.0f} weeks "
         f"(~{yrs(sum(t['weeks'] for t in wins)/len(wins)):.1f} yrs)** · losers: "
         f"{sum(t['weeks'] for t in losses)/len(losses):.0f} weeks (~{yrs(sum(t['weeks'] for t in losses)/len(losses)):.1f} yrs)",
         f"- Avg holding of the **top-10 winners: {sum(t['weeks'] for t in top10)/10:.0f} weeks "
         f"(~{yrs(sum(t['weeks'] for t in top10)/10):.1f} yrs)**\n",
         "## Top 25 winners\n",
         "| # | Symbol | Entry | Exit | Return | Held (weeks) | Held (yrs) | P&L (₹) |",
         "|--:|---|---|---|--:|--:|--:|--:|"]
    for i, t in enumerate(top, 1):
        L.append(f"| {i} | {clean(t['sym'])} | {t['entry_date']} | {t['exit_date']} | "
                 f"+{t['ret']*100:,.0f}% | {t['weeks']} | {yrs(t['weeks']):.1f} | {t['pnl']:,.0f} |")
    L += ["", "## Winners by holding period\n", "| Holding | # winners |", "|---|--:|"]
    for lo,hi,lab in buckets:
        L.append(f"| {lab} | {dist[lab]} |")
    L += ["",
          "## Read-out\n",
          "- The **biggest winners are held the longest** — the top-10 average ~"
          f"{yrs(sum(t['weeks'] for t in top10)/10):.0f}+ years, while losers are cut in well under a year. "
          "That asymmetry (ride winners, cut losers fast) is the engine of the returns.",
          "- Winners on average are held far longer than losers; the 20% trailing stop is loose enough "
          "to let multi-baggers compound for years. (A 10% trail would shorten these holds.)\n",
          "## ⚠️ Caveats\n",
          "- In-sample, survivorship-biased (today's Nifty 500) — the biggest multi-baggers are exactly "
          "the names that survived into the current index, so this list flatters the upside. Holding "
          "periods are realistic; the return magnitudes are an upper bound.\n",
          "*Generated by `backtest/top_winners.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "TOP_WINNERS.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    bt.BB_LEN = 52; bt.POS_PCT = 0.02
    print("\nWrote docs/TOP_WINNERS.md")

if __name__ == "__main__":
    main()
