#!/usr/bin/env python3
"""
Trailing-stop WIDTH sweep. Fixed base:
  entry = upper Bollinger breakout + Nifty 500 6-month RS > 0.2,
  market cap ₹1000-20000 cr, position size 4%, weekly.
Varies the ratcheting % trailing stop: 5% / 10% / 15% / 20%.
Reports CAGR and Max drawdown. Cached, deterministic. In-sample, survivorship-biased.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw2sigma_backtest as bt
import calmar_experiments as ce
import marketcap_test as mt

WIDTHS = [0.05, 0.10, 0.15, 0.20]
MLO, MHI = 1000, 20000

def main():
    symbols, data, master = ce.setup()
    mt.annotate_mcap(data, {s: v for s, v in mt.fetch_marketcaps(sorted(set(symbols))).items()})
    bt.annotate_rs(data, symbols, lookback=26, index_sym="%5ECRSLDX")
    bt.POS_PCT = 0.04
    trailonly = bt.EXIT_MODES["ATR trail only"]

    rows = []
    for w in WIDTHS:
        r = bt.simulate(symbols, data, master, trailonly, trail_type="pct", pct_trail=w,
                        rs_entry=True, rs_thresh=0.2, size_mode="fixed", max_pos=50,
                        mcap_lo=MLO, mcap_hi=MHI)
        m = bt.metrics(r["curve"], periods_per_year=52); t = bt.trade_stats(r["trades"])
        rows.append((w, m, t, r["exposure"], r["curve"]))
        print(f"{int(w*100):2d}% trail   CAGR {m['cagr']*100:5.1f}%   MaxDD {m['maxdd']*100:5.1f}%   "
              f"Calmar {m['calmar']:.2f}   Sharpe {m['sharpe']:.2f}   Trades {t.get('n',0):4d}   "
              f"Win {t.get('win_rate',0)*100:.0f}%   Exp {r['exposure']*100:3.0f}%   "
              f"Final ₹{m['end_v']:,.0f}", flush=True)
    bt.POS_PCT = 0.02

    best = max(rows, key=lambda x: x[1]["calmar"])
    n500 = [x for x in bt.fetch_weekly("%5ECRSLDX") if x[0] >= master[0]]
    n500c = [(x[0], bt.INIT_CAPITAL * x[4] / n500[0][4]) for x in n500]
    colors = {0.05: "#ef4444", 0.10: "#f59e0b", 0.15: "#22a06b", 0.20: "#2563eb"}
    series = [(f"{int(w*100)}% trail (Calmar {m['calmar']:.2f})", colors[w], cv)
              for w, m, t, e, cv in rows]
    series.append(("Nifty 500 buy&hold", "#9ca3af", n500c))
    bt.make_svg(series, os.path.join(bt.OUTDIR, "results", "trail_width_equity.svg"),
                "Trailing-stop width 5/10/15/20% (Rs 20L, log scale)")

    yrs = (master[-1] - master[0]).days / 365.25
    L = ["# Trailing-stop width sweep (5% / 10% / 15% / 20%)\n",
         "> Base: upper Bollinger breakout + Nifty 500 6-month RS > 0.2 + market cap ₹1000–20000 cr "
         "+ 4% sizing, weekly. Only the ratcheting %% trailing stop width changes. Cached, "
         "deterministic. **In-sample, survivorship-biased.**\n",
         f"- **Window:** {master[0]} → {master[-1]} ({yrs:.1f} years) · ₹20L start\n",
         "## Results by trail width\n",
         "| Trail width | **CAGR** | **Max DD** | Calmar | Sharpe | Trades | Win% | Avg invested | Final |",
         "|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
    for w, m, t, exp, _ in rows:
        star = " ⭐" if (w, m, t, exp, _) == best else ""
        L.append(f"| {int(w*100)}%{star} | {m['cagr']*100:.1f}% | {m['maxdd']*100:.1f}% | "
                 f"**{m['calmar']:.2f}** | {m['sharpe']:.2f} | {t.get('n',0)} | {t.get('win_rate',0)*100:.0f}% | "
                 f"{exp*100:.0f}% | ₹{m['end_v']:,.0f} |")
    L += ["",
          "![trail width](../backtest/results/trail_width_equity.svg)\n",
          "## Read-out\n",
          "- **Tight trails (5–10%)** get whipsawed out of winners early: many more trades, lower "
          "win rate, and usually lower CAGR — the ratchet fires on normal weekly noise.",
          "- **Wider trails (15–20%)** give winners room to run (fewer trades, higher win rate), so "
          "CAGR is higher; drawdown is a bit deeper because you give back more before exiting.",
          "- Pick the width where CAGR is strong and drawdown is still tolerable — usually 15–20% for "
          "this weekly, small/mid-cap breakout system.\n",
          "*Generated by `backtest/trail_width_sweep.py`.*"]
    with open(os.path.join(os.path.dirname(bt.OUTDIR), "docs", "TRAIL_WIDTH.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\nWrote docs/TRAIL_WIDTH.md and backtest/results/trail_width_equity.svg")

if __name__ == "__main__":
    main()
